package mas.Simulation;

public enum PutVariable {ALL, CONTROL, SETPOINT,LOADPROFILE, LOADPROFILEINFO, STARTSCHEDULING, SCHEDULINGPLAN, 
	SCHEDULINGPLANINFOS, SCHEDULINGACCEPTED, SCHEDULINGREJECTED, SCHEDULINGDONE, 
	SCHEDULINGFAILURE, SCHEDULINGREFUSE, CONTROLFAILURE, BALANCING, BALANCINGAGREE, 
	BALANCINGREFUSE,BALANCINGINFORM , BALANCINGFAILURE, ENERGYCONSUMPTIONPROFILE, 
	ACCOUNTINGECPREFERENCE, ACCOUNTINGECPRECEIVED,
	LOADTIMEWINDOWSREQUEST, LOADTIMEWINDOWSINFORM,
	FRENABLEFAILURE, FRENABLEINFORM, FRBLOCKFAILURE, FRBLOCKINFORM, FRTRIGGERED, FRENABLEREQUEST, FRBLOCKREQUEST, FRCONFIRM,
	AGENTDEAD, AGENTBORN};

